### ISSUE TITLE
time inconsistency in start 

### ISSUE THREAD

**Issue by XiaNi** [MozillaReality/ecsy-three#21]
to start all loop we need to run first
```js
world.execute(0,0)
```

which forces ecsy to use it's own "now()" polyfill
like:
```js
// performance.now() "polyfill"
export const now =
  hasWindow && typeof window.performance !== "undefined"
    ? performance.now.bind(performance)
    : Date.now.bind(Date);
```

so our first execution of systems will get time from "ecsy now() polyfill"

but then default animationLoop goes with THREE.Clock, and it can cause time jump
```js
  if (!animationLoop) {
    const clock = new THREE.Clock();
    animationLoop = () => {
      world.execute(clock.getDelta(), clock.elapsedTime);
    };
  }
```

THREE.Clock divides time by 1000
```js
			var newTime = ( typeof performance === 'undefined' ? Date : performance ).now();

			diff = ( newTime - this.oldTime ) / 1000;
			this.oldTime = newTime;

			this.elapsedTime += diff;
```

so at first "execute" time could be like 49 and second "execute" time will be like 49/1000.

since we extend world as ECSYThreeWorld we can override world.execute to use THREE.Clock by default?

**Comment by fernandojsg** [comment]
@XiaNi thanks for reporting. We fixed it by changing the resolution on ECSY core to use the same as three.js https://github.com/MozillaReality/ecsy/pull/224
