### ISSUE TITLE
Double deletion caused by obj.traverse

### ISSUE THREAD

**Issue by sam6321** [MozillaReality/ecsy-three#28]
The following line causes `EntityManager.removeEntity` to be called twice for an entity that has an `Object3D` when it is deleted.

https://github.com/MozillaReality/ecsy-three/blob/13127cb0281b4070c5f3ad6b1dd7d4a09e2cf349/src/entity.js#L150

The first invoke of the `traverse` function will be with the object itself, which calls `removeEntity`; then the end of the `remove` function, `removeEntity` is called again. (Relevant ThreeJS docs: https://threejs.org/docs/index.html#api/en/core/Object3D.traverse)

This was causing 
```
Uncaught Error: Tried to remove entity not in list
```
in the console.

Adding a self check in the traverse function to prevent the `removeEntity` call should fix that particular issue.

**Comment by sam6321** [comment]
PR: https://github.com/MozillaReality/ecsy-three/pull/29

**Comment by fernandojsg** [comment]
Nice catch @sam6321 
Although I believe it's better to just include an `else` if there is no `Object3DComponent` so there is not need to check the `obj != o` on every object we traverse:

```javascript
   if (this.hasComponent(Object3DComponent)) {
      const obj = this.getObject3D();
      obj.traverse((o) => {
        if (o.entity) {
          this._entityManager.removeEntity(o.entity, forceImmediate);
        }
        o.entity = null;
      });
      obj.parent && obj.parent.remove(obj);
    } else {
      this._entityManager.removeEntity(this, forceImmediate);
   }
```

**Comment by sam6321** [comment]
Yup, that's a better approach. I've updated the PR

**Comment by fernandojsg** [comment]
Thanks! merged
